os: linux
dist: focal

jobs:
  fast_finish: true
  include:
    - python: "3.7"
      env: TOXENV=py37
    - python: "3.8"
      env: TOXENV=py38
    - python: "3.8"
      env: TOXENV=lint

cache:
  directories:
    - $HOME/.cache/pip
install: pip install -U tox coveralls
language: python
script: travis_wait tox
after_success: coveralls
